---
title: Bookdown Syntax
author: Yutong Dai
date: '2018-05-28'
categories:
  - R-writing
tags:
  - bookdown
slug: bookdown-syntax
output:
  blogdown::html_page:
    toc: yes
summary: Introduce basic `bookdown` syntax for scientific articles.
---

> Following contents are adapeted from Yihui Xie's [bookdown](https://bookdown.org/yihui/bookdown/components.html)

# Math Equations with labels

My personal preference is to use `algin` and `equation` for long or complicated and simple expressions respectively. The slight differeces, compared with the $\bf \LaTeX$ syntax, are the way we assign labels to expressions. Instead of using `\label{foo}`, in blogdown (bookdown), it is recommend to use the syntax `(\#eq:foo)`.

Following are two simple examples. Use


```
\begin{equation}
  f(k) = \binom{n}{k} p^k(1-p)^{n-k}
  (\#eq:binom)
\end{equation}
```

to produce

\begin{equation}
  f(k) = \binom{n}{k} p^k(1-p)^{n-k}
  (\#eq:binom)
\end{equation}

Similarly, we can use \& to algin equations. 


```
\begin{align}
& f(x;\mu,\sigma) = \frac{1}{\sqrt{2\pi}}\exp(\frac{1}{2\sigma^2}(x-\mu)^2) (\#eq:gaussian)\\
& f(x;\lambda) = \lambda e^{-\lambda}I(x>0) (\#eq:exp)
\end{align}
```

\begin{align}
& f(x;\mu,\sigma) = \frac{1}{\sqrt{2\pi}}\exp(\frac{1}{2\sigma^2}(x-\mu)^2) (\#eq:gaussian)\\
& f(x;\lambda) = \lambda e^{-\lambda}I(x>0) (\#eq:exp)
\end{align}

For HTML output, bookdown can only number the equations with labels. Please make sure equations without labels are not numbered by either using the `equation*` environment or adding `\nonumber` or `\notag` to your equations. The same rules apply to other math environments, such as eqnarray, gather, align, and so on (e.g., you can use the align* environment).

To refer to a  equation, please use `\@ref(eq:label)`. For example,

```
\@ref(eq:binom)
```

can produce its index \@ref(eq:binom).



