---
title: Get Data from the Website
author: Yutong Dai
date: '2018-05-31'
categories:
  - R-Programming
tags:
  - R-tricks
slug: get-data-from-website
output:
  blogdown::html_page:
    toc: yes
summary: Use `R` funuctions to download datasets from websites and read `libsvm` formatted data. 
---



# Motivation

I'm using the datasets [libsvm](http://www.csie.ntu.edu.tw/~cjlin/libsvm/) to do some numerical experiments. The sizes of datasets, like epsilon^[https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/epsilon_normalized.bz2], are of severalGBs. So it is hard to play with the data on my desktop. I am lucky to run the experiments on a server. So my workflow is:

1. Download datasets on the server.
2. Preprocess datastes.
3. Run experiments.

The problems I encounted are

1. How to use `R` functions to download data? 
2. Since dataset files are compressed, how to uncompresse them?
3. How to read dataset are of the `libsvm` format?

# Solutions

If you only care about the way to download datasets from R, then you can stop once finish reading the following subsection.

## Download

Use built-in function `download.file`, one can finish the task.

```r
download.file(target_path, path_filename_extension)
```

For example,

```r
download.file(https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/epsilon_normalized.bz2, "./data/epsilon_normalized.bz2")
```

## Uncompress data files

Changce are that you datasets are compressed in `.zip`, `.bz2` and etc. formats, so you cannot directly load your data into the memory. You can use the function `bunzip2` from the `R.utils` packages.

```r
bunzip2(path_filet_to_uncompress, path_file_to_save, remove = FALSE, skip = TRUE)
```

- remove: If TRUE, the compressed file will be removed once uncompression finished.
- skip: If TRUE and the output file already exists, the output file is returned as is.

For example,

```
download.file("./data/epsilon_normalized.bz2", "./data/epsilon_normalized")
```
Here, the original dataset file `epsilon_normalized` has no extension.

## Load libsvm format data

The  libsvm format data is of form

```
<label> <index 1>:<value 1> <index 2>:<value 2> ... <index n>:<value n>
```
For example,

```
1 1:12 2:34 3:56
2 1:98 2:76 3:65
```
For more information, please refer to this [post](https://stats.stackexchange.com/questions/61328/libsvm-data-format).

We can use the `read.matrix.csr` function from the `e1071` package.

```r
data <- read.matrix.csr(file, fac=TRUE)
```

For example,

```r
data <- read.matrix.csr("./data/epsilon_normalized", fac=TRUE)
```
Note that `data` here is a list and matrix are stored in `sparse matrix` format. We can use `data$x` and `data$y` to extract the feature matrix and the label vector respectively.

## Complete Code

The complete code to download and uncompress data files is

```r
get_data <- function(target_path, save_path, save_name, extension, unzip=TRUE){
  path_file <- paste(save_path,save_name,sep="/")
  path_file_extension <- paste(path_file, extension, sep=".")
  download.file(target_path, path_file_extension)
  if (unzip){
    require(R.utils)
    bunzip2(path_file_extension, path_file, remove = FALSE, skip = TRUE)
    print("unzip finished!")
  }
  print(paste("data is strored at:", save_path))
}
```

The complete code to load `libsvm` format data is

```r
process_data <- function(file, convert_to_factor=FALSE){
  require(e1071)
  require(SparseM)
  print("loading data")
  data <- read.matrix.csr(file, fac=convert_to_factor)
  print("loading finished")
  x <- as.matrix(data$x)
  print("x was conveted to dense matrix form")
  y <- as.matrix(data$y)
  results <- list(x=x,y=y)
  return(results)
}
```